version: '3'

services:
  payload:
    container_name: payloadcms-dev
    image: node:18-alpine
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c 'yarn install && yarn dev'
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    container_name: payloadcms-mongo-dev
    image: mongo:5.0
    ports:
      - '${MONGO_PORT}:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
