version: '3.8'

services:
  db:
    container_name: ${POSTGRES_DOCKER_NAME}
    image: postgres:16.1-alpine
    restart: always
    ports:
    - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  # localstack:
  #   container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
  #   image: localstack/localstack:3.0
  #   ports:
  #     - '127.0.0.1:4566:${LOCALSTACK_AWS_PORT:-4566}' # LocalStack Gateway
  #     - '127.0.0.1:4510-4559:${LOCALSTACK_AWS_SERVICES_PORT_RANGE:-4510-4559}' # external services port range
  #   environment:
  #     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #     - DEBUG=${DEBUG:-0}
  #     - SERVICES=${LOCALSTACK_SERVICES:-s3}
  #   volumes:
  #     - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
  #     - '/var/run/docker.sock:/var/run/docker.sock'