version: '3.8'

services:
  db:
    container_name: strapi-postgres-dev
    image: postgres:16.1-alpine
    restart: always
    ports:
    - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
