version: '3.8'

services:
  db:
    container_name: strapi-postgres
    image: postgres:16.1-alpine
    restart: always
    ports:
    - '5432:5432'
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAMES}
